// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testCurr.Models;

namespace testCurr.Migrations
{
    [DbContext(typeof(DovizContext))]
    partial class DovizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testCurr.Models.DovizKuru", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Buying");

                    b.Property<DateTime>("Dtime");

                    b.Property<string>("Name");

                    b.Property<float>("Selling");

                    b.HasKey("Code");

                    b.ToTable("DovizKur");
                });
#pragma warning restore 612, 618
        }
    }
}
